openjdk-16-mvn-3.6.2-gradle-5.4.1-vscode

diff --git a/docker/build/Dockerfile b/docker/build/Dockerfile
--- a/docker/build/Dockerfile
+++ b/docker/build/Dockerfile
@@ -1,6 +1,32 @@
 # See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.185.0/containers/java/.devcontainer/base.Dockerfile
-FROM mcr.microsoft.com/vscode/devcontainers/java:0-8
+FROM mcr.microsoft.com/vscode/devcontainers/java:16
 
+# openjdk 8
+RUN set -eux; \
+	\
+	arch="$(dpkg --print-architecture)"; \
+	case "$arch" in \
+		'amd64') \
+			downloadUrl='https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u302-b08/OpenJDK8U-jdk_x64_linux_8u302b08.tar.gz'; \
+			;; \
+		'arm64') \
+			downloadUrl='https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries/releases/download/jdk8u302-b08/OpenJDK8U-jdk_aarch64_linux_8u302b08.tar.gz'; \
+			;; \
+		*) echo >&2 "error: unsupported architecture: '$arch'"; exit 1 ;; \
+	esac; \
+	\
+	wget --progress=dot:giga -O openjdk.tgz "$downloadUrl"; \
+	\
+    jdk8home="/usr/local/openjdk-8"; \
+	mkdir -p "$jdk8home"; \
+	tar --extract \
+		--file openjdk.tgz \
+		--directory "$jdk8home" \
+		--strip-components 1 \
+		--no-same-owner \
+    ; \
+	rm openjdk.tgz*;
+    
 # [Optional] Install Maven or Gradle
 ARG INSTALL_MAVEN="true"
 ARG MAVEN_VERSION=3.6.2
@@ -15,4 +41,4 @@ ARG NODE_VERSION="lts/*"
 RUN if [ "${INSTALL_NODE}" = "true" ]; then su vscode -c "source /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi
 
 
-COPY settings.xml /usr/local/src/apache-maven/conf/settings.xml
+COPY settings.xml ${MAVEN_HOME}/conf/settings.xml
